name: Airaaa CRD VM (Input Perintah Langsung)

on:
  workflow_dispatch:
    inputs:
      crd_command:
        description: 'Tempel seluruh baris perintah dari https://remotedesktop.google.com/headless'
        required: true

jobs:
  chrome-remote-desktop:
    runs-on: windows-latest
    timeout-minutes: 359 # Maksimum ~6 jam

    steps:
      - name: Download Perangkat Lunak (VirtualBox dan Debian ISO)
        run: |
          Write-Host "Mulai mengunduh VirtualBox dan Debian 13 ISO..."
          Invoke-WebRequest -Uri "https://download.virtualbox.org/virtualbox/7.0.18/VirtualBox-7.0.18-162988-Win.exe" -OutFile "C:\VirtualBox-Installer.exe"
          Invoke-WebRequest -Uri "https://cdimage.debian.org/cdimage/weekly-builds/amd64/iso-cd/debian-testing-amd64-netinst.iso" -OutFile "C:\debian-13-netinst.iso"
          Write-Host "Download selesai. File disimpan di C:\"

      - name: Install VirtualBox
        run: |
          Write-Host "Memulai instalasi VirtualBox secara senyap..."
          Start-Process -FilePath "C:\VirtualBox-Installer.exe" -ArgumentList "--silent" -Wait
          Write-Host "Instalasi VirtualBox selesai."

      - name: Setup Chrome Remote Desktop
        run: |
          # Download dan instal host CRD
          Invoke-WebRequest -Uri https://dl.google.com/chrome-remote-desktop/chromeremotedesktophost.msi -OutFile $env:TEMP\chromeremotedesktophost.msi
          Start-Process msiexec.exe -ArgumentList '/i', ('{0}\chromeremotedesktophost.msi' -f $env:TEMP), '/quiet' -Wait

          # Ekstrak Auth Token dan PIN dari input pengguna
          $command = "${{ github.event.inputs.crd_command }}"
          $AuthToken = $null
          $Pin = $null

          # Ekstrak Auth Token menggunakan regular expression
          if ($command -match '--code="([^"]+)"') {
              $AuthToken = $matches[1]
          }

          # Ekstrak PIN menggunakan regular expression
          if ($command -match '-pin=([0-9]+)') {
              $Pin = $matches[1]
          }

          # Periksa apakah token dan pin berhasil diekstrak
          if (-not $AuthToken -or -not $Pin) {
              Write-Error "Gagal mengekstrak Auth Token atau PIN dari perintah yang diberikan. Pastikan formatnya benar."
              exit 1
          }
          
          Write-Host "Auth Token dan PIN berhasil diekstrak. Memulai layanan CRD..."

          # Mulai host CRD menggunakan token dan pin yang diekstrak
          & "$env:ProgramFiles(x86)\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="$AuthToken" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$env:COMPUTERNAME -pin="$Pin"
          
          Write-Host "Layanan Chrome Remote Desktop berhasil dimulai."

      - name: Jaga Koneksi Tetap Aktif
        run: |
          Write-Host "===================================================================="
          Write-Host "Runner siap untuk diakses melalui Chrome Remote Desktop."
          Write-Host "Buka https://remotedesktop.google.com/access untuk terhubung."
          Write-Host "Runner akan tetap aktif selama ~6 jam atau hingga dibatalkan."
          Write-Host "File VirtualBox dan Debian ISO ada di direktori C:\"
          Write-Host "===================================================================="
          
          # Loop untuk menjaga agar runner tetap berjalan
          while ($true) {
              Start-Sleep -Seconds 600
              Write-Host "[$(Get-Date)] Sesi aktif. Batalkan alur kerja untuk menghentikan."
          }
